#!/bin/bash

################################################################################
# Dev Account Permission Assignment Script
#
# Purpose:
#   This script automatically finds all users who have been assigned the
#   TerraformDeployerPermissions (or any specified Permission Set) in any
#   existing AWS account, and grants them the same permission on the shared
#   dev account.
#
# Use Case:
#   When you create a shared "dev" account that should be accessible to all
#   developers who already have dev permissions on their personal sandbox
#   accounts, this script automates the process of:
#   1. Finding all users with the specified Permission Set
#   2. Assigning them access to the new dev account
#
# How AWS IAM Identity Center Permissions Work:
#   Permission assignments are a three-way relationship:
#     Assignment = User + Account + Permission Set
#   
#   A user can have the same Permission Set on multiple accounts.
#   This script creates new assignments for the dev account while
#   preserving existing assignments on other accounts.
#
# Usage:
#   ./assign-dev-account.sh <dev-account-id> [permission-set-name]
#
# Arguments:
#   dev-account-id      The AWS Account ID of the shared dev account
#   permission-set-name (Optional) The Permission Set to look for
#                       Default: TerraformDeployerPermissions
#
# Examples:
#   # Assign all TerraformDeployerPermissions users to dev account
#   ./assign-dev-account.sh 713608733769
#
#   # Assign users with a specific Permission Set
#   ./assign-dev-account.sh 713608733769 PowerUserPermissions
#
# Prerequisites:
#   - AWS CLI configured with management account credentials
#   - IAM Identity Center enabled
#   - jq installed
#
# Created: 2025-12-02
# Author: Generated by Cursor AI
################################################################################

set -e
set -o pipefail

################################################################################
# Configuration
################################################################################

# Color codes for output
readonly COLOR_RESET='\033[0m'
readonly COLOR_INFO='\033[0;34m'
readonly COLOR_SUCCESS='\033[0;32m'
readonly COLOR_ERROR='\033[0;31m'
readonly COLOR_WARNING='\033[0;33m'

# Script arguments
DEV_ACCOUNT_ID="${1:-}"
PERMISSION_SET_NAME="${2:-TerraformDeployerPermissions}"

################################################################################
# Helper Functions
################################################################################

log_info() {
    echo -e "${COLOR_INFO}[INFO]$(date '+%Y-%m-%d %H:%M:%S')${COLOR_RESET} $*"
}

log_success() {
    echo -e "${COLOR_SUCCESS}[SUCCESS]$(date '+%Y-%m-%d %H:%M:%S')${COLOR_RESET} $*"
}

log_error() {
    echo -e "${COLOR_ERROR}[ERROR]$(date '+%Y-%m-%d %H:%M:%S')${COLOR_RESET} $*"
}

log_warning() {
    echo -e "${COLOR_WARNING}[WARNING]$(date '+%Y-%m-%d %H:%M:%S')${COLOR_RESET} $*"
}

usage() {
    cat << EOF
Dev Account Permission Assignment Script

Usage:
  $(basename "$0") <dev-account-id> [permission-set-name]

Arguments:
  dev-account-id      The AWS Account ID of the shared dev account
  permission-set-name (Optional) Default: TerraformDeployerPermissions

Examples:
  $(basename "$0") 713608733769
  $(basename "$0") 713608733769 PowerUserPermissions

This script finds all users who have the specified Permission Set assigned
on any existing account, and grants them the same permission on the dev account.

EOF
}

################################################################################
# Prerequisite Checks
################################################################################

check_prerequisites() {
    # Check AWS CLI
    if ! command -v aws &> /dev/null; then
        log_error "AWS CLI is not installed"
        exit 1
    fi
    
    # Check jq
    if ! command -v jq &> /dev/null; then
        log_error "jq is not installed"
        exit 1
    fi
    
    # Check AWS credentials
    if ! aws sts get-caller-identity &> /dev/null; then
        log_error "AWS credentials are not configured"
        exit 1
    fi
}

################################################################################
# Main Logic
################################################################################

main() {
    # Validate arguments
    if [[ -z "${DEV_ACCOUNT_ID}" ]]; then
        log_error "Missing required argument: dev-account-id"
        usage
        exit 1
    fi
    
    check_prerequisites
    
    echo ""
    echo "════════════════════════════════════════════════════════════════════"
    echo "    Dev Account Permission Assignment"
    echo "════════════════════════════════════════════════════════════════════"
    echo ""
    log_info "Dev Account ID: ${DEV_ACCOUNT_ID}"
    log_info "Permission Set: ${PERMISSION_SET_NAME}"
    echo ""
    
    # Step 1: Get SSO Instance ARN
    log_info "Step 1: Getting IAM Identity Center instance..."
    local sso_instance_arn
    sso_instance_arn=$(aws sso-admin list-instances \
        --query 'Instances[0].InstanceArn' \
        --output text)
    
    if [[ -z "${sso_instance_arn}" ]] || [[ "${sso_instance_arn}" == "None" ]]; then
        log_error "No IAM Identity Center instance found"
        exit 1
    fi
    log_success "Instance ARN: ${sso_instance_arn}"
    
    # Step 2: Find Permission Set ARN
    log_info "Step 2: Finding Permission Set '${PERMISSION_SET_NAME}'..."
    local ps_arn=""
    local permission_sets
    permission_sets=$(aws sso-admin list-permission-sets \
        --instance-arn "${sso_instance_arn}" \
        --query 'PermissionSets[]' \
        --output text)
    
    for arn in ${permission_sets}; do
        local name
        name=$(aws sso-admin describe-permission-set \
            --instance-arn "${sso_instance_arn}" \
            --permission-set-arn "${arn}" \
            --query 'PermissionSet.Name' \
            --output text)
        
        if [[ "${name}" == "${PERMISSION_SET_NAME}" ]]; then
            ps_arn="${arn}"
            break
        fi
    done
    
    if [[ -z "${ps_arn}" ]]; then
        log_error "Permission Set '${PERMISSION_SET_NAME}' not found"
        exit 1
    fi
    log_success "Permission Set ARN: ${ps_arn}"
    
    # Step 3: Find all accounts with this Permission Set assigned
    log_info "Step 3: Finding accounts with '${PERMISSION_SET_NAME}' assigned..."
    local assigned_accounts
    assigned_accounts=$(aws sso-admin list-accounts-for-provisioned-permission-set \
        --instance-arn "${sso_instance_arn}" \
        --permission-set-arn "${ps_arn}" \
        --query 'AccountIds[]' \
        --output text 2>/dev/null || echo "")
    
    if [[ -z "${assigned_accounts}" ]]; then
        log_warning "No accounts found with '${PERMISSION_SET_NAME}' assigned"
        log_info "Nothing to do"
        exit 0
    fi
    
    local account_count
    account_count=$(echo "${assigned_accounts}" | wc -w | tr -d ' ')
    log_success "Found ${account_count} account(s) with this Permission Set"
    
    # Step 4: Collect all unique users with this Permission Set
    log_info "Step 4: Collecting users with '${PERMISSION_SET_NAME}'..."
    
    # Using a temporary file to store unique user IDs (for shell compatibility)
    local user_ids_file
    user_ids_file=$(mktemp)
    trap "rm -f ${user_ids_file}" EXIT
    
    for account_id in ${assigned_accounts}; do
        # Skip the dev account itself (in case it's already in the list)
        if [[ "${account_id}" == "${DEV_ACCOUNT_ID}" ]]; then
            log_info "  Skipping dev account: ${account_id}"
            continue
        fi
        
        log_info "  Checking account: ${account_id}"
        
        # Get all USER type assignments for this Permission Set on this account
        local assignments
        assignments=$(aws sso-admin list-account-assignments \
            --instance-arn "${sso_instance_arn}" \
            --account-id "${account_id}" \
            --permission-set-arn "${ps_arn}" \
            --output json 2>/dev/null || echo '{"AccountAssignments":[]}')
        
        # Extract USER type PrincipalIds and append to temp file
        echo "${assignments}" | jq -r '.AccountAssignments[] | select(.PrincipalType == "USER") | .PrincipalId' >> "${user_ids_file}"
    done
    
    # Get unique user IDs
    local unique_users
    unique_users=$(sort -u "${user_ids_file}" | grep -v '^$' || echo "")
    
    # Check if we found any users
    if [[ -z "${unique_users}" ]]; then
        log_warning "No users found with '${PERMISSION_SET_NAME}'"
        log_info "Nothing to do"
        exit 0
    fi
    
    local user_count
    user_count=$(echo "${unique_users}" | wc -l | tr -d ' ')
    
    echo ""
    log_success "Found ${user_count} unique user(s):"
    echo "${unique_users}" | while read -r uid; do
        echo "    - ${uid}"
    done
    echo ""
    
    # Step 5: Assign Permission Set to each user on the dev account
    log_info "Step 5: Assigning '${PERMISSION_SET_NAME}' on dev account..."
    echo ""
    
    local success_count=0
    local skip_count=0
    local fail_count=0
    
    for user_id in ${unique_users}; do
        log_info "Processing user: ${user_id}"
        
        # Check if already assigned
        local existing
        existing=$(aws sso-admin list-account-assignments \
            --instance-arn "${sso_instance_arn}" \
            --account-id "${DEV_ACCOUNT_ID}" \
            --permission-set-arn "${ps_arn}" \
            --output json 2>/dev/null | \
            jq -r ".AccountAssignments[] | select(.PrincipalId == \"${user_id}\") | .PrincipalId")
        
        if [[ -n "${existing}" ]]; then
            log_warning "  Already assigned, skipping"
            skip_count=$((skip_count + 1))
            continue
        fi
        
        # Create the assignment
        local result
        if result=$(aws sso-admin create-account-assignment \
            --instance-arn "${sso_instance_arn}" \
            --target-id "${DEV_ACCOUNT_ID}" \
            --target-type AWS_ACCOUNT \
            --permission-set-arn "${ps_arn}" \
            --principal-type USER \
            --principal-id "${user_id}" \
            --output json 2>&1); then
            
            local request_id
            request_id=$(echo "${result}" | jq -r '.AccountAssignmentCreationStatus.RequestId')
            log_info "  Assignment request: ${request_id}"
            
            # Wait for completion (simple approach - just sleep)
            sleep 3
            
            # Check status
            local status_result
            status_result=$(aws sso-admin describe-account-assignment-creation-status \
                --instance-arn "${sso_instance_arn}" \
                --account-assignment-creation-request-id "${request_id}" \
                --output json 2>/dev/null || echo '{"AccountAssignmentCreationStatus":{"Status":"UNKNOWN"}}')
            
            local status
            status=$(echo "${status_result}" | jq -r '.AccountAssignmentCreationStatus.Status')
            
            if [[ "${status}" == "SUCCEEDED" ]]; then
                log_success "  ✓ Assigned successfully"
                success_count=$((success_count + 1))
            elif [[ "${status}" == "IN_PROGRESS" ]]; then
                log_info "  ⏳ Assignment in progress (will complete shortly)"
                success_count=$((success_count + 1))
            else
                local reason
                reason=$(echo "${status_result}" | jq -r '.AccountAssignmentCreationStatus.FailureReason // "Unknown"')
                log_error "  ✗ Assignment failed: ${reason}"
                fail_count=$((fail_count + 1))
            fi
        else
            log_error "  ✗ Failed to create assignment: ${result}"
            fail_count=$((fail_count + 1))
        fi
        
        # Small delay to avoid API throttling
        sleep 1
    done
    
    # Summary
    echo ""
    echo "════════════════════════════════════════════════════════════════════"
    echo "    Summary"
    echo "════════════════════════════════════════════════════════════════════"
    echo ""
    log_info "Dev Account: ${DEV_ACCOUNT_ID}"
    log_info "Permission Set: ${PERMISSION_SET_NAME}"
    echo ""
    log_success "Successfully assigned: ${success_count}"
    log_warning "Already assigned (skipped): ${skip_count}"
    if [[ ${fail_count} -gt 0 ]]; then
        log_error "Failed: ${fail_count}"
    fi
    echo ""
    
    if [[ ${success_count} -gt 0 ]]; then
        log_info "✨ Users can now access the dev account via SSO portal"
        log_info "   They may need to refresh or re-login to see the new account"
    fi
    
    echo ""
}

# Run main function
main "$@"

